// <auto-generated />
namespace SurfLocalShop.Migrations.StoreConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class contextreset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contextreset));
        
        string IMigrationMetadata.Id
        {
            get { return "202012050831332_contextreset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
